/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  AdminLeaves: () => import('#controllers/admin_leaves_controller'),
  Auth: () => import('#controllers/auth_controller'),
  LeaveRequests: () => import('#controllers/leave_requests_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
